name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      - name: Build
        run: ./build.bat