name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Blender 3.0.0
        if: always()
        uses: ./.github/actions/build-windows
        with:
          blender-version: "3.0.0"

      - name: Blender 2.79b
        if: always()
        uses: ./.github/actions/build-windows
        with:
          blender-version: "2.79b"

      - name: Install
        if: success()
        run: cmake --build build --target INSTALL --config Release